### PR TITLE
[SAS-14] Education Page Frontend Update

### PR DESCRIPTION
**Pull request by sheldor1510**
Completed UI for 3 screens:
- Home/Initial Screen
- Search Screen
- Saved Resources Screen

https://user-images.githubusercontent.com/58443068/230209398-6fa0bcd2-4bca-462a-8c72-bc93a64d680f.mp4

### CODE REVIEW

**Review by 21pdavis — DISMISSED** [review]
Hi Anshul - this looks awesome. Great work! Could you add the actual images from the education pages in this PR?

I'm referring to these images (but copied as SVG):
image

To export as SVG in Figma, right click --> copy/paste as --> SVG (or click export in bottom right to export multiple at a time as files).

You can place these new SVGs in mobile/assets/resource_images/

Let me know if you have any trouble working with the SVGs. See #21 for an example of importing an SVG.

**Comment by sheldor1510** [comment]
@21pdavis Do you want me to export the svgs and place them in the folder or actually put them in place of the colored divs on the screen? (The current design has the colored divs and not the images, which is why I'm confused.)

**Comment by 21pdavis** [comment]
> @21pdavis Do you want me to export the svgs and place them in the folder or actually put them in place of the colored divs on the screen? (The current design has the colored divs and not the images, which is why I'm confused.)

Right, sorry for the confusion. If you could do both of those things, that would be great. So, adding those resource SVGs to the assets folder and then fitting the appropriate in place of the colored divs.

Just like this in the current design on the Figma
image

image


The Flow 3 prototype starts on that page, but if you go to home, then back to education, it updates with the correct images. The final design has the images on the main page and colored squares in the sub-pages.

**Review by ducth1903 — CHANGES_REQUESTED** [review]
Good progress! Few comments:
1. I like how you use mock data. You should also think of it as it can grow in the future. So the code should be more scalable. Perhaps use FlatList instead of hard-coding? Should be careful deciding the data structure to use for it.
2. Please squash and add ticket number to each of your commit message.

**Comment by sheldor1510** [comment]
@21pdavis I added the PNGs and put them in the screen as well (as shown below). I had to add the PNGs instead of SVGs because that is the format they were present in the figma file, even if I exported them as an SVG it was just svg code with an image embedded so it didn't make sense to export them as SVGs.

@ducth1903 I made it dynamic using the Mockdata's structure instead of hard-coding it.

Demo, after the changes:

https://user-images.githubusercontent.com/58443068/230692207-f878d9e9-77d3-48b0-a8a3-7e9a17c48c19.mp4

**Review by ducth1903 — APPROVED** [review]

**Pull request merged**
