### PR TITLE
[SAS-6] add circles for dates for home page based on Vi's Codepen

### PR DESCRIPTION
**Pull request by ducth1903**
Screen Shot 2023-04-05 at 00 48 31 Screen Shot 2023-04-05 at 00 48 49 Screen Shot 2023-04-05 at 00 49 00

Note for @vitdoan: please update this screenshot once you finish update it

Reply to @ducth1903: Updated!

### CODE REVIEW

**Review by vitdoan — DISMISSED** [review]

**Review by ducth1903 — COMMENTED** [review]
Can we try to make the date circle bigger and larger text too?
It is a bit quite small to me. @vitdoan

**Review by ducth1903 — COMMENTED** [review]
Nice! Looks good to me! Can you squash the commits into few ones, probably just one or two commits? Thanks!

**Comment by ducth1903** [comment]
Also, we should think of a data structure to store the symptoms (i.e. blood flow, mood, etc.) instead of hard-coding all.
It will be easier to add/remove any symptom and for maintenance in the future @vitdoan

**Comment by vitdoan** [comment]
> Nice! Looks good to me! Can you squash the commits into few ones, probably just one or two commits? Thanks!

Sure!

**Comment by vitdoan** [comment]
> Also, we should think of a data structure to store the symptoms (i.e. blood flow, mood, etc.) instead of hard-coding all. It will be easier to add/remove any symptom and for maintenance in the future @vitdoan

I was thinking about that as well. Do you have any suggestions? For now, I think I'll hard-code temporarily to get a general structure of the frontend and then refactor my code after finishing. 
Sorry I pushed the unfinished code up because last time I has some problem with git so I had to delete the whole local file which results in losing all my work :'(

**Review by ducth1903 — COMMENTED** [review]
Nice!

**Comment by ducth1903** [comment]
Please resolve the conflict then we can merge

**Comment by ducth1903** [comment]
Actually it is my PR so you need to approve @vitdoan lol

**Review by vitdoan — APPROVED** [review]

**Pull request merged**
